"""Domain models for the Sentri system."""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Optional


class _OracleJSONEncoder(json.JSONEncoder):
    """Handle Oracle types that aren't JSON-serializable by default."""

    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.isoformat()
        if isinstance(obj, date):
            return obj.isoformat()
        if isinstance(obj, Decimal):
            return float(obj)
        return super().default(obj)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return str(uuid.uuid4())


@dataclass
class Suggestion:
    """Output of Agent 1 (Scout). A parsed email alert."""

    alert_type: str
    database_id: str
    raw_email_subject: str
    raw_email_body: str
    extracted_data: dict
    confidence: float = 1.0
    parsed_at: str = field(default_factory=_now_iso)

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> Suggestion:
        return cls(**json.loads(s))


@dataclass
class VerificationReport:
    """Output of Agent 2 (Auditor). Validates an alert is real."""

    is_valid: bool
    confidence: float
    actual_metrics: dict
    reported_metrics: dict
    duplicate_check: bool  # True = no duplicates found
    checks_passed: list[str]
    checks_failed: list[str]
    verified_at: str = field(default_factory=_now_iso)

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> VerificationReport:
        return cls(**json.loads(s))


@dataclass
class ExecutionPlan:
    """Generated by orchestrator. Defines what Agent 4 should do."""

    action_type: str
    forward_sql: str
    rollback_sql: str
    validation_sql: str
    expected_outcome: dict
    risk_level: str
    estimated_duration_seconds: int
    params: dict = field(default_factory=dict)  # Bind params for validation SQL

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> ExecutionPlan:
        return cls(**json.loads(s))


@dataclass
class ExecutionResult:
    """Output of Agent 4 (Executor). What happened when we ran the fix."""

    success: bool
    action_sql_executed: str
    output: str
    error_message: Optional[str] = None
    rolled_back: bool = False
    rollback_output: Optional[str] = None
    metrics_before: Optional[dict] = None
    metrics_after: Optional[dict] = None
    duration_seconds: float = 0.0
    executed_at: str = field(default_factory=_now_iso)

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> ExecutionResult:
        return cls(**json.loads(s))


@dataclass
class Workflow:
    """Central tracking object. One per alert. Stored in workflows table."""

    id: str = field(default_factory=_new_id)
    alert_type: str = ""
    database_id: str = ""
    environment: str = ""
    status: str = "DETECTED"
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

    # Agent outputs (JSON strings)
    suggestion: Optional[str] = None
    verification: Optional[str] = None
    execution_plan: Optional[str] = None
    execution_result: Optional[str] = None

    # Approval tracking
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None
    approval_timeout: Optional[str] = None

    # Metadata
    metadata: Optional[str] = None

    # v2.0: severity classification
    severity: Optional[str] = None


@dataclass
class AuditRecord:
    """Immutable audit log entry. Append-only."""

    workflow_id: str
    action_type: str
    database_id: str
    environment: str
    executed_by: str
    result: str

    action_sql: Optional[str] = None
    approved_by: Optional[str] = None
    error_message: Optional[str] = None
    evidence: Optional[str] = None  # JSON: metrics before/after
    change_ticket: Optional[str] = None

    id: Optional[int] = None
    timestamp: Optional[str] = None


@dataclass
class EnvironmentRecord:
    """Database environment registry entry."""

    database_id: str
    database_name: str
    environment: str
    connection_string: str

    oracle_version: Optional[str] = None
    architecture: Optional[str] = None  # STANDALONE, CDB, RAC
    autonomy_level: Optional[str] = None
    critical_schemas: Optional[str] = None  # JSON array
    business_owner: Optional[str] = None
    dba_owner: Optional[str] = None
    created_at: Optional[str] = None
    last_verified: Optional[str] = None

    # v2.0: Database profiling
    database_profile: Optional[str] = None  # JSON blob from Agent 0
    profile_version: int = 0
    profile_updated_at: Optional[str] = None


@dataclass
class DatabaseProfile:
    """Output of Agent 0 (Profiler). JSON-serializable DB profile."""

    database_id: str
    db_type: str = ""  # OLTP, OLAP, MIXED
    db_size_gb: float = 0.0
    omf_enabled: bool = False
    is_rac: bool = False
    is_cdb: bool = False
    con_id: int = 0  # Container ID: 0/1=CDB$ROOT, >1=PDB
    critical_parameters: dict = field(default_factory=dict)
    workload_metrics: dict = field(default_factory=dict)
    risk_areas: list = field(default_factory=list)
    non_standard_params: dict = field(default_factory=dict)
    db_config: dict = field(default_factory=dict)  # Raw discovery data for LLM
    profiled_at: str = field(default_factory=_now_iso)
    version: int = 1

    def to_json(self) -> str:
        return json.dumps(asdict(self), cls=_OracleJSONEncoder)

    @classmethod
    def from_json(cls, s: str) -> DatabaseProfile:
        return cls(**json.loads(s))


@dataclass
class PreFlightCheck:
    """A single pre-flight check result (used by enhanced Agent 4)."""

    name: str
    sql: str
    expected: str
    actual: Optional[str] = None
    passed: bool = False
    error: Optional[str] = None

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> PreFlightCheck:
        return cls(**json.loads(s))


@dataclass
class ResearchOption:
    """A single remediation option generated by Agent 3 (Researcher)."""

    option_id: str = field(default_factory=_new_id)
    title: str = ""
    description: str = ""
    forward_sql: str = ""
    rollback_sql: str = ""
    confidence: float = 0.0
    risk_level: str = "MEDIUM"
    reasoning: str = ""
    source: str = "template"  # "template" or "llm"

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> ResearchOption:
        return cls(**json.loads(s))


@dataclass
class LearningObservation:
    """An observation captured by Agent 5 (Analyst) for learning."""

    workflow_id: str
    alert_type: str
    database_id: str
    observation_type: str  # EXECUTION_OUTCOME, FALSE_POSITIVE, ROLLBACK, etc.
    data: str  # JSON blob with details

    id: Optional[int] = None
    status: str = "CAPTURED"  # CAPTURED, PROCESSED, APPLIED, REJECTED
    created_at: Optional[str] = None
    processed_at: Optional[str] = None

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> LearningObservation:
        return cls(**json.loads(s))
